In [ ]:
### 
'''
Understanding Axes in NumPy Arrays
One-dimensional arrays:
    For a 1D array, axis=0 is the only axis, representing the entire array.
Two-dimensional arrays:
    axis=0 corresponds to the rows (vertical direction)
    axis=1 corresponds to the columns (horizontal direction)
Three-dimensional arrays and beyond:
    axis=0 is the first dimension (think of it as depth)
    axis=1 is the second dimension (rows)
    axis=2 is the third dimension (columns)
'''
### 

In [2]:
import numpy as np

In [10]:
arr_1d = np.array([1, 2, 3, 4])
print(arr_1d)
print('Number of dimensions',arr_1d.ndim)  # Number of dimensions
print('Shape', arr_1d.shape)  # Shape
print('Sum along axis 0', arr_1d.sum(axis=0))  # Sum along axis 0 (entire array)
# Output: 10

[1 2 3 4]
Number of dimensions 1
Shape (4,)
Sum along axis 0 10


In [11]:
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6]])
print(arr_2d)
print('Number of dimensions',arr_2d.ndim)  # Number of dimensions
print('Shape', arr_2d.shape)  # Shape

print(arr_2d.sum(axis=0))  # Sum along axis 0 (columns)
# Output: [5 7 9]

print(arr_2d.sum(axis=1))  # Sum along axis 1 (rows)
# Output: [ 6 15]

[[1 2 3]
 [4 5 6]]
Number of dimensions 2
Shape (2, 3)
[5 7 9]
[ 6 15]


In [ ]:
arr_3d = np.array([[[1, 2, 3], [4, 5, 6]],
                   [[6, 7, 8], [9, 10, 11]]])
print(arr_3d)
print('Number of dimensions',arr_3d.ndim)  # Number of dimensions
print('Shape', arr_3d.shape)  # Shape


print(arr_3d.sum(axis=0))  # Sum along first dimension
# Output: 
# [[ 7  9 11]
# [13 15 17]]

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 6  7  8]
  [ 9 10 11]]]
Number of dimensions 3
Shape (2, 2, 3)
[[ 7  9 11]
 [13 15 17]]
