In [1]:
import pandas as pd
import numpy as np
from sklearn.datasets import load_iris

##### **iris_load()**

In [2]:
'''
iris_load() is a function returns a dictionary-like object, often referred to as a Bunch object, which contains the dataset and its attributes:
Attributes:
data: The feature matrix (usually a 2D numpy array) containing the dataset's features.
target: The target vector (usually a 1D numpy array) containing the class labels for each sample.
feature_names: The list of feature names (column names) in the dataset.
target_names: The list of target names (class labels) in the dataset.
DESCR: A full description of the dataset.
filename: The path to the location of the dataset file.
'''

"\niris_load() is a function returns a dictionary-like object, often referred to as a Bunch object, which contains the dataset and its attributes:\nAttributes:\ndata: The feature matrix (usually a 2D numpy array) containing the dataset's features.\ntarget: The target vector (usually a 1D numpy array) containing the class labels for each sample.\nfeature_names: The list of feature names (column names) in the dataset.\ntarget_names: The list of target names (class labels) in the dataset.\nDESCR: A full description of the dataset.\nfilename: The path to the location of the dataset file.\n"

In [3]:
# Load the Iris dataset
iris = load_iris() # For Basic Data Access and Exploration: Use the default load_iris() to get the data in a Bunch object (It returns a Bunch object).
iris_df = load_iris(as_frame=True) # For Data Analysis and Visualization: Use load_iris(as_frame=True) to get a pandas DataFrame.
iris_X_y = load_iris(return_X_y=True) # For Direct Model Training: Use load_iris(return_X_y=True) to get the feature and target arrays directly (returns a tuple of two NumPy arrays: (X, y)).

In [4]:
# This show the data we get in a Bunch object; containing Data (as NumPy array), Target (as NumPy array), Feature_names (as a list), Target_names (as a list)
# DESCR (as a string description) and Filename (as a string path) 
iris

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

In [5]:
# Access and print the content of the Bunch object 
print("Keys of Bunch object:")
print(iris.keys())

Keys of Bunch object:
dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])


In [6]:
print(f'The data type of the "data" attribute: {type(iris['data'])}')
print(f'The number of dimensions of the "data" array (matrix): {iris['data'].ndim}')
print(f'The shape of the "data" array: {iris['data'].shape}')

The data type of the "data" attribute: <class 'numpy.ndarray'>
The number of dimensions of the "data" array (matrix): 2
The shape of the "data" array: (150, 4)


In [7]:
print(f'The data type of the "target" attribute: {type(iris['target'])}')
print(f'The number of dimensions of the "target" array (matrix): {iris['target'].ndim}')
print(f'The shape of the "target" array: {iris['target'].shape}')

The data type of the "target" attribute: <class 'numpy.ndarray'>
The number of dimensions of the "target" array (matrix): 1
The shape of the "target" array: (150,)


In [8]:
print(f'The data type of iris.data: {type(iris.data)}')
iris.data[:5] # Or you can use iris['data']

The data type of iris.data: <class 'numpy.ndarray'>


array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2]])

In [9]:
# Access the feature matrix
data = iris['data']  # or iris.data
print(f'The data type of iris["data"]: {type(iris['data'])}\n')
print("The Features matrix (data):")
data[:5]

The data type of iris["data"]: <class 'numpy.ndarray'>

The Features matrix (data):


array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2]])

In [10]:
print(f'The data type of iris.target: {type(iris.target)}')
iris.target # Or you can use iris['target]

The data type of iris.target: <class 'numpy.ndarray'>


array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [11]:
# Access the target vector
target = iris['target']  # or iris.target
print(f'The data type of iris["target"]: {type(iris['target'])}')
print("\nTarget vector (target):\n", target)

The data type of iris["target"]: <class 'numpy.ndarray'>

Target vector (target):
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


In [12]:
# Access the feature names
feature_names = iris['feature_names']  # or iris.feature_names
print(f'The data type of the iris["feature_names"]: {type(iris['feature_names'])}')
print("The names of the Features:\n", feature_names)

The data type of the iris["feature_names"]: <class 'list'>
The names of the Features:
 ['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']


In [13]:
# Access the target names
target_names = iris['target_names']  # or iris.target_names
print(f'The data type of the iris["target_names"]: {type(iris['target_names'])}')
print("The names of the Target (target or class labels):\n", target_names)

The data type of the iris["target_names"]: <class 'numpy.ndarray'>
The names of the Target (target or class labels):
 ['setosa' 'versicolor' 'virginica']


In [14]:
# Access the description of the dataset
description = iris['DESCR']  # or iris.DESCR
print("Dataset description:\n", description)

Dataset description:
 .. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

:Number of Instances: 150 (50 in each of three classes)
:Number of Attributes: 4 numeric, predictive attributes and the class
:Attribute Information:
    - sepal length in cm
    - sepal width in cm
    - petal length in cm
    - petal width in cm
    - class:
            - Iris-Setosa
            - Iris-Versicolour
            - Iris-Virginica

:Summary Statistics:

============== ==== ==== ======= ===== ====================
                Min  Max   Mean    SD   Class Correlation
============== ==== ==== ======= ===== ====================
sepal length:   4.3  7.9   5.84   0.83    0.7826
sepal width:    2.0  4.4   3.05   0.43   -0.4194
petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)
============== ==== ==== ======= ===== ====================

:Missing Attribute Values: None
:Class Distribution: 33.3% for 

In [15]:
# Access the filename
filename = iris['filename']  # or iris.filename
print("Dataset filename:\n", filename)

Dataset filename:
 iris.csv


In [16]:
# This show the data we get as pandas DataFrame with the feature and target data
iris_df

{'data':      sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
 0                  5.1               3.5                1.4               0.2
 1                  4.9               3.0                1.4               0.2
 2                  4.7               3.2                1.3               0.2
 3                  4.6               3.1                1.5               0.2
 4                  5.0               3.6                1.4               0.2
 ..                 ...               ...                ...               ...
 145                6.7               3.0                5.2               2.3
 146                6.3               2.5                5.0               1.9
 147                6.5               3.0                5.2               2.0
 148                6.2               3.4                5.4               2.3
 149                5.9               3.0                5.1               1.8
 
 [150 rows x 4 columns],
 'target': 0     

In [17]:
# "data" as pandas DataFrame
iris_df['data'].head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [18]:
print(f"The data type of the 'data' attribute: {type(iris_df['data'])}")
print(f"The number of dimensions of the 'data' array (matrix): {iris_df['data'].ndim}")
print(f"The shape of the 'data' array (features matrix): {iris_df['data'].shape}")

The data type of the 'data' attribute: <class 'pandas.core.frame.DataFrame'>
The number of dimensions of the 'data' array (matrix): 2
The shape of the 'data' array (features matrix): (150, 4)


In [19]:
# "data" as pandas DataFrame
iris_df['target'].head()

0    0
1    0
2    0
3    0
4    0
Name: target, dtype: int64

In [20]:
print(f'The data type of the "target" attribute: {type(iris_df['target'])}')
print(f'The number of dimensions of the "target" array (matrix): {iris_df['target'].ndim}')
print(f'The shape of the "target" array: {iris_df['target'].shape}')

The data type of the "target" attribute: <class 'pandas.core.series.Series'>
The number of dimensions of the "target" array (matrix): 1
The shape of the "target" array: (150,)


In [21]:
# # The attribute "frame" represents both features and target in one DataFrame
iris_df['frame'].head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   target  
0       0  
1       0  
2       0  
3       0  
4       0

In [22]:
# Important: You can use the following to create a pandas DataFrame including both faetures and target of iris dataset
iris_df = load_iris(as_frame=True).frame

In [23]:
# This show Bunch including the "Tuple" of two NumPy arrays: (X, y).
# X: A NumPy array of shape (150, 4) containing the feature data.
# y: A NumPy array of shape (150,) containing the target values.
# This format is suitable for directly feeding the data into machine learning algorithms that expect NumPy arrays as input.
iris_X_y

(array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
        [5

In [24]:
iris_X_y[0][:5]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2]])

In [25]:
print(f'The data type of the X attribute: {type(iris_X_y[0])}')
print(f'The number of dimensions of the X array (matrix): {iris_X_y[0].ndim}')
print(f'The shape of the X array: {iris_X_y[0].shape}')

The data type of the X attribute: <class 'numpy.ndarray'>
The number of dimensions of the X array (matrix): 2
The shape of the X array: (150, 4)


In [26]:
iris_X_y[1]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [27]:
print(f'The data type of the y attribute: {type(iris_X_y[1])}')
print(f'The number of dimensions of the y array (matrix): {iris_X_y[1].ndim}')
print(f'The shape of the y array: {iris_X_y[1].shape}')

The data type of the y attribute: <class 'numpy.ndarray'>
The number of dimensions of the y array (matrix): 1
The shape of the y array: (150,)


##### **train_test_split()**

In [28]:
from sklearn.model_selection import train_test_split

In [29]:
# train_test_split(arrays: )
# *arrays : sequence of indexables with same length / shape[0]
# Allowed inputs are lists, numpy arrays, scipy-sparse matrices or pandas dataframes.

##### # Splitting the data into training and testing sets using [NumPy arrays]

In [30]:
# A - Note: One way to load the Iris dataset with features (X) and target (y) as separate arrays
X = iris_X_y[0]
y = iris_X_y[1]

# B - Note: Another way to load the Iris dataset with features (X) and target (y) as separate arrays
X = iris.data
y = iris.target

In [31]:
# Splitting the data into training and testing sets using NumPy arrays
X_train, X_test, y_train, y_test = train_test_split(iris_X_y[0], iris_X_y[1], test_size=0.2, random_state=42, shuffle=True) # Or use X, y

In [32]:
print(f'X_train: {X_train.shape}')
print(f'X_test: {X_test.shape}')
print(f'y_train: {y_train.shape}')
print(f'y_test: {y_test.shape}')


X_train: (120, 4)
X_test: (30, 4)
y_train: (120,)
y_test: (30,)


##### # Splitting the data into training and testing sets using [Pandas DataFrame]

In [33]:
# *arrays: pandas DataFrames
train_df, test_df = train_test_split(iris_df, test_size=0.2, random_state=42, shuffle=True)

In [34]:
print(f'X_train: {train_df.shape}')
print(f'X_test: {test_df.shape}')


X_train: (120, 5)
X_test: (30, 5)


<style> .small-text { font-size: 14px; } </style> <p class="small-text"> 
The Iris dataset from sklearn is a classic dataset for classification tasks, with 150 samples of iris flowers described by 4 features: sepal length, sepal width, petal length, and petal width. The goal is to classify the flowers into one of three species.

##### **Model Selection**

<style> .small-text { font-size: 13px; } </style> <p class="small-text"> 
A- Linear Models: 

1- Logistic Regression

In [35]:
from sklearn.linear_model import LogisticRegression

logistic_regression_model = LogisticRegression()

In [36]:
logistic_regression_model.fit(X=X_train, y=y_train)

LogisticRegression()

In [37]:
y_pred = logistic_regression_model.predict(X=X_test)

In [38]:
prediction_df_columns = list(iris['feature_names'])
prediction_df_columns.extend(['Target', 'Predictions'])
predictions_np_array = np.concatenate((X_test, y_test.reshape(-1, 1), y_pred.reshape(-1, 1)), axis=1)
predictions_df = pd.DataFrame(data=predictions_np_array, columns=prediction_df_columns)
predictions_df.head(10)

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                6.1               2.8                4.7               1.2   
1                5.7               3.8                1.7               0.3   
2                7.7               2.6                6.9               2.3   
3                6.0               2.9                4.5               1.5   
4                6.8               2.8                4.8               1.4   
5                5.4               3.4                1.5               0.4   
6                5.6               2.9                3.6               1.3   
7                6.9               3.1                5.1               2.3   
8                6.2               2.2                4.5               1.5   
9                5.8               2.7                3.9               1.2   

   Target  Predictions  
0     1.0          1.0  
1     0.0          0.0  
2     2.0          2.0  
3     1.0          1.0  
4     1.0          1.0  
5     0.0          0.0  
6     1.0          1.0  
7     2.0          2.0  
8     1.0          1.0  
9     1.0          1.0

In [39]:
index_list = predictions_df.loc[predictions_df['Target'] != predictions_df['Predictions']].index
print(f'Number of not corrected predictions: {len(index_list)}')

Number of not corrected predictions: 0


In [40]:
from sklearn.metrics import mean_squared_error, accuracy_score, classification_report

mse = mean_squared_error(y_true=y_test, y_pred=y_pred)
print(f'Mean Squared Error: {mse}%')

Mean Squared Error: 0.0%


In [41]:
accuracy = accuracy_score(y_true=y_test, y_pred=y_pred)
print("Accuracy:", accuracy)

Accuracy: 1.0


In [42]:
print("\nClassification Report:\n", classification_report(y_true=y_test, y_pred=y_pred))


Classification Report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       1.00      1.00      1.00         9
           2       1.00      1.00      1.00        11

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30



In [43]:
# Optional: Predict class probabilities
y_probs = logistic_regression_model.predict_proba(X_test)
print("\nPredicted Probabilities:\n", y_probs)


Predicted Probabilities:
 [[3.80366675e-03 8.27739542e-01 1.68456791e-01]
 [9.46969747e-01 5.30300543e-02 1.98774873e-07]
 [8.86029729e-09 1.54854019e-03 9.98451451e-01]
 [6.48546697e-03 7.92228600e-01 2.01285933e-01]
 [1.45768003e-03 7.74128412e-01 2.24413908e-01]
 [9.55899676e-01 4.41001477e-02 1.76045334e-07]
 [7.80156868e-02 9.07701293e-01 1.42830204e-02]
 [1.63870749e-04 1.54555675e-01 8.45280454e-01]
 [2.22394473e-03 7.62851513e-01 2.34924542e-01]
 [2.84394195e-02 9.45735859e-01 2.58247218e-02]
 [4.45484058e-04 2.42557408e-01 7.56997108e-01]
 [9.68124830e-01 3.18750918e-02 7.79534105e-08]
 [9.73005359e-01 2.69946077e-02 3.31820454e-08]
 [9.61905950e-01 3.80939389e-02 1.10700557e-07]
 [9.79285388e-01 2.07145477e-02 6.44550338e-08]
 [4.59483811e-03 7.12372778e-01 2.83032384e-01]
 [7.31656392e-06 2.41374502e-02 9.75855233e-01]
 [2.73617560e-02 9.47767057e-01 2.48711867e-02]
 [8.26145678e-03 8.31673616e-01 1.60064927e-01]
 [1.43613957e-05 3.58380620e-02 9.64147577e-01]
 [9.64169177e

In [44]:
predictions_probability_array = np.concatenate((predictions_np_array, np.round(y_probs, 2)), axis=1)
prediction_df_columns.extend([f'Class_{i}_prob' for i in range(y_probs.shape[1])])
predictions_probability_df = pd.DataFrame(data=predictions_probability_array, columns=prediction_df_columns)

In [ ]:
predictions_probability_df

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                 6.1               2.8                4.7               1.2   
1                 5.7               3.8                1.7               0.3   
2                 7.7               2.6                6.9               2.3   
3                 6.0               2.9                4.5               1.5   
4                 6.8               2.8                4.8               1.4   
5                 5.4               3.4                1.5               0.4   
6                 5.6               2.9                3.6               1.3   
7                 6.9               3.1                5.1               2.3   
8                 6.2               2.2                4.5               1.5   
9                 5.8               2.7                3.9               1.2   
10                6.5               3.2                5.1               2.0   
11                4.8               3.0                1.4               0.1   
12                5.5               3.5                1.3               0.2   
13                4.9               3.1                1.5               0.1   
14                5.1               3.8                1.5               0.3   
15                6.3               3.3                4.7               1.6   
16                6.5               3.0                5.8               2.2   
17                5.6               2.5                3.9               1.1   
18                5.7               2.8                4.5               1.3   
19                6.4               2.8                5.6               2.2   
20                4.7               3.2                1.6               0.2   
21                6.1               3.0                4.9               1.8   
22                5.0               3.4                1.6               0.4   
23                6.4               2.8                5.6               2.1   
24                7.9               3.8                6.4               2.0   
25                6.7               3.0                5.2               2.3   
26                6.7               2.5                5.8               1.8   
27                6.8               3.2                5.9               2.3   
28                4.8               3.0                1.4               0.3   
29                4.8               3.1                1.6               0.2   

    Target  Predictions  Class_0_prob  Class_1_prob  Class_2_prob  
0      1.0          1.0          0.00          0.83          0.17  
1      0.0          0.0          0.95          0.05          0.00  
2      2.0          2.0          0.00          0.00          1.00  
3      1.0          1.0          0.01          0.79          0.20  
4      1.0          1.0          0.00          0.77          0.22  
5      0.0          0.0          0.96          0.04          0.00  
6      1.0          1.0          0.08          0.91          0.01  
7      2.0          2.0          0.00          0.15          0.85  
8      1.0          1.0          0.00          0.76          0.23  
9      1.0          1.0          0.03          0.95          0.03  
10     2.0          2.0          0.00          0.24          0.76  
11     0.0          0.0          0.97          0.03          0.00  
12     0.0          0.0          0.97          0.03          0.00  
13     0.0          0.0          0.96          0.04          0.00  
14     0.0          0.0          0.98          0.02          0.00  
15     1.0          1.0          0.00          0.71          0.28  
16     2.0          2.0          0.00          0.02          0.98  
17     1.0          1.0          0.03          0.95          0.02  
18     1.0          1.0          0.01          0.83          0.16  
19     2.0          2.0          0.00          0.04          0.96  
20     0.0          0.0          0.96          0.04          0.00  
21     2.0          2.0    