In [2]:
import numpy as np

In [3]:
# Constructing a one-dimensional array
array1 = np.array([1, 2, 3, 4])
print(array1.shape)
print(array1.shape[0])
print(array1.dtype)
print(array1.ndim)
print(array1.size)

(4,)
4
int64
1
4


In [4]:
# Constructing a two-dimensional array
array2 = np.array([[1, 2, 3, 4],
                   [5, 6, 7, 8]])
print(array2.shape)
print(array2.shape[0])
print(array2.shape[1])
print(array2.dtype)
print(array2.ndim)
print(array2.size)

(2, 4)
2
4
int64
2
8


In [5]:
# Array indexing
array2[1,1]

np.int64(6)

In [6]:
# Array indexing
array2[1,:]

array([5, 6, 7, 8])

In [7]:
# Array indexing
array2[1,:2]

array([5, 6])

In [8]:
# Constructing a three-dimensional array
array3 = np.array([[[1, 2, 3, 4],
                    [5, 6, 7, 8]],
                    [[9, 10, 11, 12],
                    [13, 14, 15, 16]]])
print(array3.shape)
print(array3.shape[0])
print(array3.shape[1])
print(array3.shape[2])
print(array3.dtype)
print(array3.ndim)
print(array3.size)

(2, 2, 4)
2
2
4
int64
3
16


##### **Indexing**

In [9]:
# Indexing a three-dimensional array (dimension, row, column)
array3[0, 0, 0]

np.int64(1)

In [10]:
# Indexing a three-dimensional array (dimension, row, column)
array3[1, 1, 3]

np.int64(16)

In [11]:
# Constructing a one-dimensional array and reshaping it into two-dimensional array with a shape of (row = 4, column = 12)
array_a = np.arange(0, 48, 1)
array_a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47])

In [12]:
print(array_a.shape)

(48,)


In [51]:
array_a = array_a.reshape(4, 12)
array_a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47]])

In [52]:
array_a[:, 0:4]

array([[ 0,  1,  2,  3],
       [12, 13, 14, 15],
       [24, 25, 26, 27],
       [36, 37, 38, 39]])

In [16]:
# [Very important: An advanced types of array indexing] 
# Indexing method to select specific columns or rows. An Example on indexing specific columns 
# Indexing along an axis (e.g. column) by using a second array containing integers.
array_a[:, [0, 2, 9]]

array([[ 0,  2,  9],
       [12, 14, 21],
       [24, 26, 33],
       [36, 38, 45]])

In [17]:
# Indexing arrays with the help of boolean masks (using a boolean array as a mask)
array_a[:, [True, False, False, True, False, False, False, False, False, False, False, False]]

array([[ 0,  3],
       [12, 15],
       [24, 27],
       [36, 39]])

In [18]:
# Combination of boolean mask indexing with comparison operators
print(array_a[:,:] > 10)

[[False False False False False False False False False False False  True]
 [ True  True  True  True  True  True  True  True  True  True  True  True]
 [ True  True  True  True  True  True  True  True  True  True  True  True]
 [ True  True  True  True  True  True  True  True  True  True  True  True]]


In [54]:
print(array_a[:,:] > 5)

[[False False False False False False  True  True  True  True  True  True]
 [ True  True  True  True  True  True  True  True  True  True  True  True]
 [ True  True  True  True  True  True  True  True  True  True  True  True]
 [ True  True  True  True  True  True  True  True  True  True  True  True]]


In [19]:
print(array_a[array_a[:,:] > 5])

[ 6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29
 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47]


In [53]:
print(array_a[1:3,:] > 5)

[[ True  True  True  True  True  True  True  True  True  True  True  True]
 [ True  True  True  True  True  True  True  True  True  True  True  True]]


##### **Element-wise Operations**

In [31]:
A = np.arange(1, 5, 1)
B = np.arange(5, 9, 1)

In [40]:
A = A.reshape(2, 2)
A

array([[1, 2],
       [3, 4]])

In [41]:
B = B.reshape(2, 2)
B

array([[5, 6],
       [7, 8]])

In [42]:
# Element-wise operations with arrays (addition)
A+B

array([[ 6,  8],
       [10, 12]])

In [43]:
# Element-wise operations with arrays (multiplication)
A*B

array([[ 5, 12],
       [21, 32]])

In [44]:
# Element-wise operations with an array and a scalar (multiplication)
2*A

array([[2, 4],
       [6, 8]])

In [46]:
# Element-wise operations with an array and a scalar (addition)
2+A

array([[3, 4],
       [5, 6]])

In [47]:
# Element-wise operations with an array and a scalar (subtraction)
A-1

array([[0, 1],
       [2, 3]])

In [48]:
# Element-wise operations with an array and a scalar (division)
A/2

array([[0.5, 1. ],
       [1.5, 2. ]])

In [45]:
# Element-wise exponentiation (the square of each element in the array)
A**2

array([[ 1,  4],
       [ 9, 16]])

In [50]:
# Element-wise square root (the square root of each value in the array)
np.sqrt(A)

array([[1.        , 1.41421356],
       [1.73205081, 2.        ]])

In [55]:
# Element-wise addition with broadcasting (NumPy can broadcast the smaller array to match the size of the larger array)
A = np.array([[1, 2],
              [3, 4],
              [5, 6]])
B = np.array([2, 3])

C = A + B
C

array([[3, 5],
       [5, 7],
       [7, 9]])

In [69]:
# Axis-wise operations 
A = np.array(
    [[2, 4, 6, 8],
     [0, 1, 0, 1],
     [0, 2, 2, 2], 
     [0, 1, 1, 1]]
     )

In [70]:
# axis=None, this will sum all of the elements of the input array
print(np.sum(A))

31


In [71]:
print(np.sum(A, axis= 0))

[ 2  8  9 12]


In [72]:
print(np.sum(A, axis= 1))

[20  2  6  3]


In [74]:
print(np.mean(A))

1.9375


In [73]:
print(np.mean(A, axis= 0))

[0.5  2.   2.25 3.  ]


In [75]:
print(np.mean(A, axis= 1))

[5.   0.5  1.5  0.75]


In [76]:
# Matrix Multiplication
A = np.array([[1, 2], 
              [3, 1]])
B = np.array([[2, 3], 
              [1, 3]])

In [78]:
c = A @ B
c

array([[ 4,  9],
       [ 7, 12]])

In [80]:
E = np.dot(A, B)
E

array([[ 4,  9],
       [ 7, 12]])

In [97]:
A = np.array([[1, 2], 
              [3, 2]])
B = np.array([[2, 0], 
              [1, 1]])

In [98]:
C1 = np.transpose(A + B)
C2 = np.transpose(A) + np.transpose(B)
print(C1)
print(C2)

[[3 4]
 [2 3]]
[[3 4]
 [2 3]]


In [99]:
C3 = np.transpose(A @ B)
C4 = np.transpose(B) @ np.transpose(A)
print(C3)
print(C4)

[[4 8]
 [2 2]]
[[4 8]
 [2 2]]
